# Generated by Django 3.1.4 on 2020-12-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_auto_20201222_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='company_website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
