# Generated by Django 3.1.4 on 2020-12-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_auto_20201222_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinformation',
            name='service_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('rent', 'Rent a car')], max_length=40),
        ),
    ]
