# Generated by Django 3.1.4 on 2020-12-22 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_auto_20201222_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providercontact',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.provider'),
        ),
        migrations.AlterField(
            model_name='serviceinformation',
            name='service_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('rent', 'Rent a car')], max_length=40, null=True),
        ),
    ]
