# Generated by Django 3.1.4 on 2020-12-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_auto_20201222_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinformation',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.provider'),
        ),
    ]
