# Generated by Django 3.1.4 on 2020-12-22 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_serviceinformation_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinformation',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.provider'),
        ),
    ]
