# Generated by Django 3.1.4 on 2020-12-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_auto_20201222_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinformation',
            name='status',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('rent', 'Rent a car')], max_length=40),
        ),
    ]
