# Generated by Django 3.1.4 on 2020-12-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_auto_20201222_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providercontact',
            options={'verbose_name': 'Main Contact', 'verbose_name_plural': 'Main Contacts'},
        ),
        migrations.AlterModelOptions(
            name='serviceinformation',
            options={'verbose_name': 'Service Information', 'verbose_name_plural': 'Service Informations'},
        ),
        migrations.AlterModelOptions(
            name='socialpages',
            options={'verbose_name': 'Provider Information', 'verbose_name_plural': 'Provider Informations'},
        ),
    ]
