# Generated by Django 3.1.4 on 2020-12-22 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0012_auto_20201222_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Provider Information', 'verbose_name_plural': 'Provider Informations'},
        ),
        migrations.AlterModelOptions(
            name='socialpages',
            options={},
        ),
        migrations.AlterField(
            model_name='serviceinformation',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.provider'),
        ),
    ]
