# Generated by Django 3.1.4 on 2020-12-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0015_auto_20201222_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinformation',
            name='status',
            field=models.CharField(choices=[('0', 'Waiting'), ('1', 'Approve'), ('2', 'Cancel')], default=0, max_length=40),
        ),
    ]
