# Generated by Django 3.1.4 on 2020-12-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0017_auto_20201222_1909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialPages',
            new_name='SocialLink',
        ),
        migrations.AlterField(
            model_name='providercontact',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
