# Generated by Django 3.1.4 on 2020-12-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0018_auto_20201222_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=40),
        ),
    ]
