# Generated by Django 3.1.4 on 2020-12-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0022_auto_20201223_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providercontact',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
